import pandas as pd 
oct21 = pd.read_csv('C:/Users/manra/OneDrive/Desktop/google_cyclistic_csv_files/202110-divvy-tripdata.csv') 
#print(oct21.info())
nov21 = pd.read_csv('C:/Users/manra/OneDrive/Desktop/google_cyclistic_csv_files/202111-divvy-tripdata.csv') 
#print(nov21.info())
dec21 = pd.read_csv('C:/Users/manra/OneDrive/Desktop/google_cyclistic_csv_files/202112-divvy-tripdata.csv')
#print(dec21.info())
jan22 = pd.read_csv('C:/Users/manra/OneDrive/Desktop/google_cyclistic_csv_files/202201-divvy-tripdata.csv')
#print(jan22.info())
feb22 = pd.read_csv('C:/Users/manra/OneDrive/Desktop/google_cyclistic_csv_files/202202-divvy-tripdata.csv')
#print(feb22.info())
mar22 = pd.read_csv('C:/Users/manra/OneDrive/Desktop/google_cyclistic_csv_files/202203-divvy-tripdata.csv')
#print(mar22.info())
apr22 = pd.read_csv('C:/Users/manra/OneDrive/Desktop/google_cyclistic_csv_files/202204-divvy-tripdata.csv')
#print(apr22.info())
may22 = pd.read_csv('C:/Users/manra/OneDrive/Desktop/google_cyclistic_csv_files/202205-divvy-tripdata.csv')
#print(may22.info())
jun22 = pd.read_csv('C:/Users/manra/OneDrive/Desktop/google_cyclistic_csv_files/202206-divvy-tripdata.csv')
#print(jun22.info())
jul22 = pd.read_csv('C:/Users/manra/OneDrive/Desktop/google_cyclistic_csv_files/202207-divvy-tripdata.csv')
#print(jul22.info())
aug22 = pd.read_csv('C:/Users/manra/OneDrive/Desktop/google_cyclistic_csv_files/202208-divvy-tripdata.csv')
#print(aug22.info())
sep22 = pd.read_csv('C:/Users/manra/OneDrive/Desktop/google_cyclistic_csv_files/202209-divvy-publictripdata.csv')
#print(sep22.info())
aggregated_all_year_data=pd.concat([oct21,nov21,dec21,jan22,feb22,mar22,apr22,may22,jun22,jul22,aug22,sep22],ignore_index=True)
print(aggregated_all_year_data.info() , aggregated_all_year_data.head())
aggregated_all_year_data.to_csv('C:/Users/manra/OneDrive/Desktop/google_cyclistic_csv_files/aggregated_all_year_data.csv',index=False)